files: ^(app/api|app/errors|app/main)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/PyCQA/bandit 
    rev: '1.7.4'
    hooks:
    -   id: bandit