version: "3"

services:
  dbserver:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: code_template
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
  code_template:
    image: code_template
    build: .
    ports:
      - 8000:5000
    environment:
      - SECRET_KEY=b'i\x03\xa0E\x88j\xd3\xbc\xd7\xc8\xda\xd0\x9f\xbd\x16\x80\x96<\x89\xc5dv\xcc|'
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_CONFIG=default
      - DATABASE_URL=mysql+pymysql://root:password@dbserver/code_template
    links:
      - dbserver
  # unittest: #for running tests
  #   build:
  #     context: .
  #     target: unittest
  #   ports:
  #     - 8008:5000
  #   links:
  #     - code_template
  #   networks:
  #     - net
networks:
  net:
    driver: bridge
