apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: code_template:local
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: SECRET_KEY
              value: b'i\x03\xa0E\x88j\xd3\xbc\xd7\xc8\xda\xd0\x9f\xbd\x16\x80\x96<\x89\xc5dv\xcc|'
            - name: FLASK_ENV
              value: development
            - name: FLASK_DEBUG
              value: "true"
            - name: FLASK_CONFIG
              value: default
            - name: DATABASE_URL
              value: mysql+pymysql://root:password@mysql/code_template
