global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['template-prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "mysql-exporter"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['template-mysql-exporter:9104']

  - job_name: 'code_template'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['code_template:5000']

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
    # basic_auth:
    #   username: '<Your Grafana Username>'
    #   password: '<Your Grafana API key>'
